name: CI Pipeline with Auto Release and DEB Packaging

on:
  push:
    branches: [master]  # или main — зависит от твоей ветки
  workflow_dispatch:     # позволяет запускать вручную через GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ googletest libgtest-dev git dpkg-dev

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Create DEB package
        run: |
          mkdir -p deb/DEBIAN deb/usr/local/bin
          cp build/character_example deb/usr/local/bin/
          echo "Package: herobuilder" > deb/DEBIAN/control
          echo "Version: 1.0" >> deb/DEBIAN/control
          echo "Section: base" >> deb/DEBIAN/control
          echo "Priority: optional" >> deb/DEBIAN/control
          echo "Architecture: amd64" >> deb/DEBIAN/control
          echo "Maintainer: Your Name <you@example.com>" >> deb/DEBIAN/control
          echo "Description: Example of Builder Design Pattern in C++" >> deb/DEBIAN/control
          echo "Depends: libc6 (>= 2.34)" >> deb/DEBIAN/control
          dpkg-deb --build deb hero-builder.deb

      - name: Create GitHub Release and Upload DEB
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          files: hero-builder.deb
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
